site_name: Cemiyet
theme: readthedocs
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Data Specification: data-specification.md
  - Roadmap: roadmap.md
  - Backend: back-end.md
  - API Docs: /cemiyet/api-docs
