site_name: Cemiyet
theme: readthedocs
nav:
  - Home: index.md
  - Backend:
      - Roadmap: backend/roadmap.md
      - Modules: backend/modules.md
      - Data Specification: backend/data-specification.md
  - Frontend:
      - Roadmap: frontend/roadmap.md
      - Frontend: frontend/frontend.md
